// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleSellingProject.WebApplication.Models;

namespace VehicleSellingProject.WebApplication.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20220503231149_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VehicleSellingProject.WebApplication.Models.EngineDetails", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("Code");

                    b.Property<byte>("Cylinders")
                        .HasColumnType("tinyint")
                        .HasColumnName("Cylinders");

                    b.Property<int>("EngineSize")
                        .HasColumnType("int")
                        .HasColumnName("EngineSize");

                    b.HasKey("Id");

                    b.ToTable("EngineDetails");
                });

            modelBuilder.Entity("VehicleSellingProject.WebApplication.Models.SedanVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<byte>("EngineDetailsId")
                        .HasColumnType("tinyint")
                        .HasColumnName("EngineDetailsCode");

                    b.Property<int>("Model")
                        .HasColumnType("int")
                        .HasColumnName("Model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("EngineDetailsId");

                    b.ToTable("Sedan");
                });

            modelBuilder.Entity("VehicleSellingProject.WebApplication.Models.SedanVehicle", b =>
                {
                    b.HasOne("VehicleSellingProject.WebApplication.Models.EngineDetails", "EngineDetails")
                        .WithMany("SedanVehicles")
                        .HasForeignKey("EngineDetailsId")
                        .HasConstraintName("FK_Sedan_EngineDetails")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EngineDetails");
                });

            modelBuilder.Entity("VehicleSellingProject.WebApplication.Models.EngineDetails", b =>
                {
                    b.Navigation("SedanVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
